#!/usr/bin/env node
import {chromium} from '../../web/node_modules/playwright/index.mjs';
import {createServer} from 'node:http';import {readFile,mkdir,writeFile} from 'node:fs/promises';import path from 'node:path';import assert from 'node:assert/strict';
const root=path.resolve('planet-port/dist'),out=path.resolve('planet-port/build/network-test');await mkdir(out,{recursive:true});
const html=slot=>`<!doctype html><meta charset="utf-8"><canvas id="canvas" width="640" height="480"></canvas><script>window.logs=[];window.errors=[];window.Module={canvas:document.querySelector('canvas'),arguments:['Easy.c4f/Goldmine.c4s','Objects.c4d','Player0.c4p','Player1.c4p'],print:(...x)=>logs.push(x.join(' ')),printErr:(...x)=>errors.push(x.join(' ')),onAbort:e=>errors.push(String(e)),onRuntimeInitialized(){for(let i=0;i<2;i++){Module.FS.mkdir('/data/Player'+i+'.c4p');Module.FS.writeFile('/data/Player'+i+'.c4p/Player.txt','[Player]\\r\\nName=Player'+i+'\\r\\nRankName=Beginner\\r\\n[Preferences]\\r\\nControl=0\\r\\nColor='+i+'\\r\\n');}window.configured=Module.ccall('nc_browser_net_configure','number',['number','number','number'],[424242,${slot},2]);}};</script><script src="planet.js"></script>`;
const server=createServer(async(req,res)=>{try{let url=new URL(req.url,'http://localhost');if(url.pathname==='/'){res.setHeader('Content-Type','text/html');res.end(html(Number(url.searchParams.get('slot'))));return;}let file=path.resolve(root,'.'+url.pathname);if(!file.startsWith(root+'/'))throw Error();res.setHeader('Content-Type',file.endsWith('.js')?'text/javascript':file.endsWith('.wasm')?'application/wasm':'application/octet-stream');res.end(await readFile(file));}catch{res.writeHead(404);res.end();}});await new Promise(r=>server.listen(0,'127.0.0.1',r));
const browser=await chromium.launch({executablePath:'/opt/google/chrome/chrome',headless:true,args:['--no-sandbox','--use-angle=swiftshader','--enable-unsafe-swiftshader']});let pages=[];const report={};
try{
 pages=await Promise.all([browser.newPage(),browser.newPage()]);await Promise.all(pages.map(async(p,i)=>{p.on('pageerror',e=>console.error('page',i,String(e)));await p.goto('http://127.0.0.1:'+server.address().port+'/?slot='+i);await p.waitForFunction(()=>window.configured===1&&window.Module?._nc_planet_state&&JSON.parse(Module.ccall('nc_planet_state','string',[],[])).ready,null,{timeout:60000});}));
 const snapshot=p=>p.evaluate(()=>({state:JSON.parse(Module.ccall('nc_planet_state','string',[],[])),network:JSON.parse(Module.ccall('nc_browser_net_status','string',[],[])),errors,logs}));
 report.initial=await Promise.all(pages.map(snapshot));for(let i=0;i<2;i++){assert.equal(report.initial[i].network.frame,0);assert.equal(report.initial[i].network.playersJoined,true);assert.equal(report.initial[i].state.players.filter(p=>p.local).length,1);assert.equal(report.initial[i].state.players.find(p=>p.local).number,i);}
 const bytes=async(p,suffix,args=[])=>p.evaluate(({suffix,args})=>{let ptr=Module.ccall('nc_browser_net_'+suffix,'number',args.map(()=>'number'),args),n=Module._nc_browser_net_size();return ptr&&n?Array.from(Module.HEAPU8.subarray(ptr,ptr+n)):null;},{suffix,args});
 const sync=()=>Promise.all(pages.map(p=>bytes(p,'sync')));
 report.initialSync=await sync();assert.deepEqual(...report.initialSync);
 for(let frame=0;frame<180;frame++){
  if(frame%40===0)for(let slot=0;slot<2;slot++)await pages[slot].evaluate(({slot,frame})=>Module.ccall('nc_planet_control','number',Array(4).fill('number'),[slot,frame%80===0?(slot?6:8):7,1,0]),{slot,frame});
  for(let slot=0;slot<2;slot++){const data=await bytes(pages[slot],'drain');if(data)assert.equal(await pages[0].evaluate(({slot,data})=>Module.ccall('nc_browser_net_admit','number',['number','array','number'],[slot,data,data.length]),{slot,data}),1);}
  const data=await bytes(pages[0],'build',[frame]);assert.ok(data&&data.length>=17);
  const results=await Promise.all(pages.map(p=>p.evaluate(({data,frame})=>{const a=Module.ccall('nc_browser_net_accept','number',['number','array','number'],[frame,data,data.length]);const delta=Module._nc_planet_step(1);return {a,delta};},{data,frame})));for(const r of results){assert.equal(r.a,1);assert.equal(r.delta,1);}
  if(frame%20===19)assert.deepEqual(...await sync(),'native checks diverged after frame'+(frame+1));
 }
 report.final=await Promise.all(pages.map(snapshot));report.finalSync=await sync();assert.deepEqual(...report.finalSync);
 const malformed=Array(17).fill(0);report.malformed=await pages[0].evaluate(data=>Module.ccall('nc_browser_net_admit','number',['number','array','number'],[1,data,data.length]),malformed);assert.equal(report.malformed,-2);
 await pages[1].evaluate(()=>Module._nc_planet_control(1,8,1,0));const foreign=await bytes(pages[1],'drain');report.foreign=await pages[0].evaluate(data=>Module.ccall('nc_browser_net_admit','number',['number','array','number'],[0,data,data.length]),foreign);assert.equal(report.foreign,-2);
 report.pass=true;console.log('PASS: two original Planet instances, 180 ordered frames, both player inputs, sync equality, packet validation');
}catch(e){report.failure=String(e.stack||e);console.error(report.failure);process.exitCode=1;}finally{for(let i=0;i<pages.length;i++){try{await pages[i].screenshot({path:out+'/peer'+i+'.png'});report['peer'+i]=await pages[i].evaluate(()=>({logs,errors,state:JSON.parse(Module.ccall('nc_planet_state','string',[],[])),net:JSON.parse(Module.ccall('nc_browser_net_status','string',[],[]))}));}catch{}}await writeFile(out+'/report.json',JSON.stringify(report,null,2));await browser.close();server.close();}
