import test from 'node:test';
import assert from 'node:assert/strict';
import {createHmac} from 'node:crypto';
import {createService} from '../src/service.js';
import {MemoryStore} from '../src/store.js';
import {turnProvider} from '../src/turn.js';
const base={name:'Gold Mine',scenario:'Worlds.c4f/GoldMine.c4s',version:'test-1',catalog:'digest',maxPlayers:2,visibility:'public'};
function fixture(options={}){let now=100000;const store=new MemoryStore(()=>now);const handle=createService({store,clock:()=>now,ipLimit:10000,...options});const call=(action,data={},token='')=>handle({action,...data},{token,ip:'127.0.0.1'});return {store,call,tick:n=>{now+=n;}};}
async function pair(f){const host=await f.call('create',base);const guest=await f.call('join',{code:host.code,name:'Guest',version:base.version,catalog:base.catalog});return {host,guest};}
const rejected=(p,code)=>assert.rejects(p,e=>e.code===code);
test('public discovery excludes private and incompatible rooms, tokens remain private',async()=>{const f=fixture();const a=await f.call('create',base);await f.call('create',{...base,visibility:'private'});const list=await f.call('list',base);assert.equal(list.rooms.length,1);assert.equal(list.rooms[0].code,a.code);assert.equal(JSON.stringify(list).includes(a.token),false);assert.deepEqual((await f.call('list',{...base,version:'other'})).rooms,[]);await rejected(f.call('poll',{code:a.code},'wrong'),'unauthorized');const serialized=await f.store.get(a.code);assert.equal(serialized.includes(a.token),false);});
test('simultaneous joins atomically enforce capacity and campaign version',async()=>{const f=fixture(),host=await f.call('create',base);await rejected(f.call('join',{code:host.code,name:'Guest',version:'wrong',catalog:base.catalog}),'version_mismatch');const results=await Promise.allSettled(Array.from({length:10},(_,i)=>f.call('join',{code:host.code,name:'Guest'+i,version:base.version,catalog:base.catalog})));assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal(JSON.parse(await f.store.get(host.code)).guests.length,1);});
test('host/guest signaling permissions and generation restart reject stale SDP',async()=>{const f=fixture({turn:async()=>({iceServers:[],expiresAt:999999})}),{host,guest}=await pair(f);const common={code:host.code,slot:guest.slot,generation:0};await rejected(f.call('signal',{...common,kind:'offer',description:{type:'offer',sdp:'v=0\r\n'}},guest.token),'signal_role');await f.call('signal',{...common,kind:'offer',description:{type:'offer',sdp:'v=0\r\nhost'}},host.token);await f.call('signal',{...common,kind:'answer',description:{type:'answer',sdp:'v=0\r\nguest'}},guest.token);const poll=await f.call('poll',{code:host.code},guest.token);assert.equal(poll.offer.sdp,'v=0\r\nhost');assert.equal(poll.rtcToken,guest.rtcToken);await rejected(f.call('turn',common,guest.token),'relay_not_needed');await f.call('signal',{...common,kind:'relay'},guest.token);await f.call('signal',{...common,kind:'relay'},host.token);const restarted=await f.call('poll',{code:host.code},guest.token);assert.equal(restarted.generation,1);assert.equal(restarted.offer,null);await rejected(f.call('signal',{...common,kind:'answer',description:{type:'answer',sdp:'v=0\r\n'}},guest.token),'stale_signal');});
test('TURN credentials require member token, coalesce retries and recover from provider failure',async()=>{let issued=0;const f=fixture({turn:async()=>{issued++;if(issued===1)throw Error('provider down');return {iceServers:[{urls:['turn:example.test'],username:'short',credential:'secret'}],expiresAt:1000000};}}),{host,guest}=await pair(f),data={code:host.code,slot:guest.slot};await rejected(f.call('turn',data,'wrong'),'unauthorized');await f.call('signal',{...data,kind:'relay'},guest.token);await rejected(f.call('turn',data,guest.token),'relay_unavailable');const result=await f.call('turn',data,guest.token);assert.equal(result.iceServers[0].credential,'secret');assert.deepEqual(await f.call('turn',data,guest.token),result);assert.equal(issued,2);const hostPoll=await f.call('poll',{code:host.code},host.token);assert.equal(JSON.stringify(hostPoll).includes('credential'),false);await f.call('signal',{...data,kind:'offer',generation:1,description:{type:'offer',sdp:'v=0\r\nhost'}},host.token);await f.call('signal',{...data,kind:'answer',generation:1,description:{type:'answer',sdp:'v=0\r\nguest'}},guest.token);await f.call('connected',data,host.token);await rejected(f.call('turn',data,guest.token),'relay_not_needed');});
test('pending guests expire without keeping absent host alive; start only by host',async()=>{const f=fixture(),{host,guest}=await pair(f);await rejected(f.call('start',{code:host.code},guest.token),'host_only');f.tick(90001);assert.equal((await f.call('poll',{code:host.code},host.token)).guests.length,0);await rejected(f.call('poll',{code:host.code},guest.token),'unauthorized');f.tick(180001);await rejected(f.call('poll',{code:host.code},host.token),'room_expired');const second=await pair(f);await f.call('start',{code:second.host.code},second.host.token);await rejected(f.call('poll',{code:second.host.code},second.guest.token),'room_expired');});
test('admission and byte budgets fail closed, request budget resets after30days',async()=>{const f=fixture({requestLimit:2});await f.call('list',base);await f.call('list',base);await rejected(f.call('list',base),'budget_exhausted');f.tick(2592000001);assert.deepEqual(await f.call('list',base),{rooms:[]});const b=fixture({byteLimit:1});await b.call('list',base);await rejected(b.call('list',base),'budget_exhausted');});
test('rate limit does not consume accepted-request budget; invalid body and oversized SDP rejected',async()=>{const limited=fixture({ipLimit:1});await limited.call('list',base);await rejected(limited.call('list',base),'rate_limited');assert.equal(limited.store.used,1);const f=fixture(),{host,guest}=await pair(f);await rejected(f.call('signal',{code:host.code,slot:guest.slot,kind:'offer',generation:0,description:{type:'offer',sdp:'v=0'+'x'.repeat(48000)}},host.token),'invalid_sdp');});
test('coturn credentials use timestamp HMAC and never expose shared secret',async()=>{const issue=turnProvider({TURN_PROVIDER:'coturn',TURN_SHARED_SECRET:'only-server-knows',TURN_URLS:'turn:relay.example:3478',TURN_TTL_SECONDS:'7200'});const result=await issue({identity:'room-peer',now:100000});assert.equal(result.iceServers[0].username,'7300:room-peer');assert.equal(result.iceServers[0].credential,createHmac('sha1','only-server-knows').update('7300:room-peer').digest('base64'));assert.equal(JSON.stringify(result).includes('only-server-knows'),false);});

test('left guest slots are reused within original engine range with fresh credentials',async()=>{const f=fixture(),host=await f.call('create',base);let previous;for(let i=0;i<15;i++){const guest=await f.call('join',{code:host.code,name:'Guest',version:base.version,catalog:base.catalog});assert.equal(guest.slot,1);assert.notEqual(guest.rtcToken,previous);previous=guest.rtcToken;await f.call('leave',{code:host.code},guest.token);}});

async function exchange(f,host,guest){const data={code:host.code,slot:guest.slot,generation:0};await f.call('signal',{...data,kind:'offer',description:{type:'offer',sdp:'v=0\r\nhost'}},host.token);await f.call('signal',{...data,kind:'answer',description:{type:'answer',sdp:'v=0\r\nguest'}},guest.token);}
test('connected claims require signaling and host confirmation; stale connected guests expire',async()=>{const f=fixture(),{host,guest}=await pair(f),data={code:host.code,slot:guest.slot};await rejected(f.call('connected',data,guest.token),'missing_signal');await exchange(f,host,guest);await f.call('connected',data,guest.token);assert.equal((await f.call('poll',{code:host.code},host.token)).guests[0].connected,false);await f.call('connected',data,host.token);f.tick(120000);assert.equal((await f.call('poll',{code:host.code,connectedPeers:[{slot:guest.slot,rtcToken:guest.rtcToken}]},host.token)).guests.length,1);f.tick(120000);assert.equal((await f.call('poll',{code:host.code},host.token)).guests.length,1);f.tick(61000);assert.equal((await f.call('poll',{code:host.code},host.token)).guests.length,0);});
test('host drop is atomic, requires matching identity and forbids guest or slot redirection',async()=>{const f=fixture(),host=await f.call('create',{...base,maxPlayers:3});const join=()=>f.call('join',{code:host.code,name:'Guest',version:base.version,catalog:base.catalog}),guest=await join(),other=await join(),data={code:host.code,slot:guest.slot,rtcToken:guest.rtcToken};await rejected(f.call('drop',data,guest.token),'host_only');await rejected(f.call('connected',{code:host.code,slot:other.slot},guest.token),'invalid_slot');await rejected(f.call('poll',{code:host.code,connectedPeers:[]},guest.token),'host_only');await f.call('drop',data,host.token);const replacement=await join();assert.equal(replacement.slot,guest.slot);await rejected(f.call('drop',data,host.token),'stale_player');assert.equal((await f.call('poll',{code:host.code},host.token)).guests.length,2);await rejected(f.call('drop',{code:host.code,slot:99,rtcToken:guest.rtcToken},host.token),'player_expired');});
test('relay TTL defaults to four hours and clamps at twelve hours',async()=>{const env={TURN_PROVIDER:'coturn',TURN_SHARED_SECRET:'secret',TURN_URLS:'turn:relay.example:3478'};assert.equal((await turnProvider(env)({identity:'test',now:0})).expiresAt,14400000);assert.equal((await turnProvider({...env,TURN_TTL_SECONDS:'999999'})({identity:'test',now:0})).expiresAt,43200000);});

test('host live-peer poll recovers a lost connected notification without refreshing mismatched identities',async()=>{const f=fixture(),{host,guest}=await pair(f);await exchange(f,host,guest);let state=await f.call('poll',{code:host.code,connectedPeers:[{slot:guest.slot,rtcToken:'x'.repeat(32)}]},host.token);assert.equal(state.guests[0].connected,false);state=await f.call('poll',{code:host.code,connectedPeers:[{slot:guest.slot,rtcToken:guest.rtcToken}]},host.token);assert.equal(state.guests[0].connected,true);assert.equal(state.guests[0].offer,null);await f.call('connected',{code:host.code},guest.token);});
