#!/usr/bin/env python3
"""Export the already staged browser game to a standalone GitHub Pages artifact."""
from pathlib import Path
import argparse
import json
import shutil

ROOT = Path(__file__).resolve().parents[1]
PUBLIC = ROOT / 'web/public'
MARKER = '.neoclonk-pages-export'
# Only these published game assets are allowed into the artifact. No backend,
# repository metadata, environment files, node_modules, or previous prototypes.
DIRECTORIES = ('rage', 'icons', 'licenses')
FILES = ('apple-touch-icon.png', 'scenarios.md')
BLOCKED = {'.git', '.openai', '.wrangler', 'node_modules', '__pycache__', 'archive', 'archived', 'legacy'}

HTML = '''<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="theme-color" content="#171812">
<meta name="description" content="Play Clonk Rage in the browser. 80 original scenarios with classic controls and multiplayer.">
<meta name="application-name" content="Neoclonk">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Neoclonk">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
<link rel="manifest" href="manifest.json">
<link rel="icon" href="rage/clonk.ico">
<link rel="icon" type="image/png" sizes="192x192" href="icons/neoclonk-192.png">
<link rel="apple-touch-icon" sizes="180x180" href="apple-touch-icon.png">
<title>Neoclonk — Play Clonk Rage in the browser.</title>
<style>:root{color-scheme:dark;background:#11120f}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;overflow:hidden}main{position:fixed;inset:0;height:100dvh}iframe{display:block;width:100%;height:100%;border:0}</style>
<script src="pages-shell.js?v=zoom-buttons-1" defer></script>
</head>
<body><main><iframe id="game" title="Neoclonk — original Clonk Rage scenarios" allow="fullscreen; autoplay; gamepad" allowfullscreen></iframe><noscript>Enable JavaScript to play Neoclonk.</noscript></main></body>
</html>
'''
SCRIPT = ''''use strict';
(() => {
 const input=new URLSearchParams(location.search),query=new URLSearchParams();
 query.set('v','zoom-buttons-1');
 for(const key of ['debug','touch','replay','play','solo','load','host','join'])if(input.get(key)==='1')query.set(key,'1');
 const scenario=input.get('scenario');
 if(scenario&&/^[a-z0-9_./-]+$/i.test(scenario)&&!scenario.split('/').includes('..'))query.set('scenario',scenario);
 const save=input.get('save');
 if(save&&/\\.c4s$/i.test(save)&&save.split('/').every(part=>part&&part!=='.'&&part!=='..'&&!/[\\\\\\0]/.test(part)))query.set('save',save);
 const room=input.get('room');
 if(room&&/^[A-Z0-9]{4,10}$/i.test(room)){query.set('room',room.toUpperCase());query.set('join','1');}
 const game=new URL('rage/index.html',location.href);game.search=query.toString();game.hash='';
 document.getElementById('game').src=game.href;
})();
'''


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--output', default=str(ROOT / '_site'))
    args = parser.parse_args()
    out = Path(args.output).resolve()
    if out == ROOT or out in ROOT.parents or out == PUBLIC or PUBLIC in out.parents or out in PUBLIC.parents:
        raise SystemExit('Output must be a separate artifact directory, outside web/public.')
    required = ('rage/index.html', 'rage/clonk.js', 'rage/clonk.wasm', 'rage/clonk.data',
                'rage/catalog/scenarios.json', 'rage/source/browser-port-sources.zip', 'manifest.json')
    for name in required:
        if not (PUBLIC / name).is_file():
            raise SystemExit(f'Missing staged asset: {name}. Run rage-port/scripts/install-web.py first.')
    if out.exists():
        if any(out.iterdir()) and not (out / MARKER).is_file():
            raise SystemExit('Refusing to overwrite an unrecognized output directory.')
        shutil.rmtree(out)
    out.mkdir(parents=True)
    (out / MARKER).write_text('Generated by tools/build-pages.py; safe to rebuild.\n')
    (out / '.nojekyll').touch()

    def copy(source, destination):
        if source.is_symlink():
            raise SystemExit(f'Symlinks are not permitted in a Pages artifact: {source}')
        if source.is_dir():
            for child in sorted(source.iterdir()):
                if child.name.startswith('.') or child.name in BLOCKED:
                    continue
                copy(child, destination / child.name)
        else:
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)

    for name in (*DIRECTORIES, *FILES):
        source = PUBLIC / name
        if not source.exists():
            raise SystemExit(f'Missing published asset: {name}')
        copy(source, out / name)
    manifest = json.loads((PUBLIC / 'manifest.json').read_text())
    for key in ('id', 'start_url', 'scope'):
        manifest[key] = './'
    for icon in manifest['icons']:
        icon['src'] = icon['src'].lstrip('/')
        if not (out / icon['src']).is_file():
            raise SystemExit('Manifest icon is missing: ' + icon['src'])
    (out / 'manifest.json').write_text(json.dumps(manifest, indent=2) + '\n')
    (out / 'index.html').write_text(HTML)
    (out / 'pages-shell.js').write_text(SCRIPT)
    # Invitations currently link directly to the native shell. Give that page
    # the same app metadata, with paths relative to its /rage/ location.
    shell = out / 'rage/index.html'
    metadata = '''<link rel="manifest" href="../manifest.json">
<link rel="icon" href="clonk.ico">
<link rel="apple-touch-icon" sizes="180x180" href="../apple-touch-icon.png">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-title" content="Neoclonk">
<meta name="apple-mobile-web-app-status-bar-style" content="black">
'''
    shell.write_text(shell.read_text().replace('</head>', metadata + '</head>', 1))
    files = [p for p in out.rglob('*') if p.is_file()]
    total = sum(p.stat().st_size for p in files)
    largest = max(p.stat().st_size for p in files)
    if total >= 1_000_000_000:
        raise SystemExit('Pages artifact exceeds the 1 GB limit.')
    print(json.dumps({'output': str(out), 'files': len(files), 'bytes': total, 'largestFileBytes': largest}))


if __name__ == '__main__':
    main()
